"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['/Users/orujahmadov/Desktop/Pixels/Pixels.py']
OPTIONS = {'argv_emulation': True,
            'iconfile':'Pixels.icns'}

setup(
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
